CREATE TABLE [dbo].[ADRC](
	[TAS_RP_INSERT_DATE] [varchar](20) NOT NULL,
	[TAS_RP_CHANGE_DATE] [varchar](20) NOT NULL,
	[TAS_RP_OPCODE] [char](1) NOT NULL,
	[TAS_RP_CYCLEID] [varchar](20) NOT NULL,
	[TAS_RP_COMMIT_SCN] [varchar](20) NULL,
	[CLIENT] [char](3) NOT NULL,
	[ADDRNUMBER] [varchar](10) NOT NULL,
	[DATE_FROM] [varchar](8) NOT NULL,
	[NATION] [char](1) NOT NULL,
	[DATE_TO] [varchar](8) NULL,
	[TITLE1] [char](4) NULL,
	[NAME1] [varchar](40) NULL,
	[NAME2] [varchar](40) NULL,
	[NAME3] [varchar](40) NULL,
	[NAME4] [varchar](40) NULL,
	[NAME_TEXT] [varchar](50) NULL,
	[NAME_CO] [varchar](40) NULL,
	[CITY1] [varchar](40) NULL,
	[CITY2] [varchar](40) NULL,
	[CITY_CODE] [varchar](12) NULL,
	[CITYP_CODE] [varchar](8) NULL,
	[HOME_CITY] [varchar](40) NULL,
	[CITYH_CODE] [varchar](12) NULL,
	[CHCKSTATUS] [char](1) NULL,
	[REGIOGROUP] [varchar](8) NULL,
	[POST_CODE1] [varchar](10) NULL,
	[POST_CODE2] [varchar](10) NULL,
	[POST_CODE3] [varchar](10) NULL,
	[PCODE1_EXT] [varchar](10) NULL,
	[PCODE2_EXT] [varchar](10) NULL,
	[PCODE3_EXT] [varchar](10) NULL,
	[PO_BOX] [varchar](10) NULL,
	[DONT_USE_P] [char](4) NULL,
	[PO_BOX_NUM] [char](1) NULL,
	[PO_BOX_LOC] [varchar](40) NULL,
	[CITY_CODE2] [varchar](12) NULL,
	[PO_BOX_REG] [char](3) NULL,
	[PO_BOX_CTY] [char](3) NULL,
	[POSTALAREA] [varchar](15) NULL,
	[TRANSPZONE] [varchar](10) NULL,
	[STREET] [varchar](60) NULL,
	[DONT_USE_S] [char](4) NULL,
	[STREETCODE] [varchar](12) NULL,
	[STREETABBR] [char](2) NULL,
	[HOUSE_NUM1] [varchar](10) NULL,
	[HOUSE_NUM2] [varchar](10) NULL,
	[HOUSE_NUM3] [varchar](10) NULL,
	[STR_SUPPL1] [varchar](40) NULL,
	[STR_SUPPL2] [varchar](40) NULL,
	[STR_SUPPL3] [varchar](40) NULL,
	[LOCATION] [varchar](40) NULL,
	[BUILDING] [varchar](20) NULL,
	[FLOOR] [varchar](10) NULL,
	[ROOMNUMBER] [varchar](10) NULL,
	[COUNTRY] [char](3) NULL,
	[LANGU] [char](2) NULL,
	[REGION] [char](3) NULL,
	[ADDR_GROUP] [char](4) NULL,
	[FLAGGROUPS] [char](1) NULL,
	[PERS_ADDR] [char](1) NULL,
	[SORT1] [varchar](20) NULL,
	[SORT2] [varchar](20) NULL,
	[SORT_PHN] [varchar](20) NULL,
	[DEFLT_COMM] [char](3) NULL,
	[TEL_NUMBER] [varchar](30) NULL,
	[TEL_EXTENS] [varchar](10) NULL,
	[FAX_NUMBER] [varchar](30) NULL,
	[FAX_EXTENS] [varchar](10) NULL,
	[FLAGCOMM2] [char](1) NULL,
	[FLAGCOMM3] [char](1) NULL,
	[FLAGCOMM4] [char](1) NULL,
	[FLAGCOMM5] [char](1) NULL,
	[FLAGCOMM6] [char](1) NULL,
	[FLAGCOMM7] [char](1) NULL,
	[FLAGCOMM8] [char](1) NULL,
	[FLAGCOMM9] [char](1) NULL,
	[FLAGCOMM10] [char](1) NULL,
	[FLAGCOMM11] [char](1) NULL,
	[FLAGCOMM12] [char](1) NULL,
	[FLAGCOMM13] [char](1) NULL,
	[ADDRORIGIN] [char](4) NULL,
	[MC_NAME1] [varchar](25) NULL,
	[MC_CITY1] [varchar](25) NULL,
	[MC_STREET] [varchar](25) NULL,
	[EXTENSION1] [varchar](40) NULL,
	[EXTENSION2] [varchar](40) NULL,
	[TIME_ZONE] [varchar](6) NULL,
	[TAXJURCODE] [varchar](15) NULL,
	[ADDRESS_ID] [varchar](10) NULL,
	[LANGU_CREA] [char](1) NULL,
	[ADRC_UUID] [varchar](16) NULL,
	[UUID_BELATED] [char](1) NULL,
	[ID_CATEGORY] [char](1) NULL,
	[ADRC_ERR_STATUS] [char](1) NULL,
	[PO_BOX_LOBBY] [varchar](40) NULL,
	[DELI_SERV_TYPE] [char](4) NULL,
	[DELI_SERV_NUMBER] [varchar](10) NULL,
	[COUNTY_CODE] [varchar](8) NULL,
	[COUNTY] [varchar](40) NULL,
	[TOWNSHIP_CODE] [varchar](8) NULL,
	[TOWNSHIP] [varchar](40) NULL,
	[MC_COUNTY] [varchar](25) NULL,
	[MC_TOWNSHIP] [varchar](25) NULL,
	[XPCPT] [char](1) NULL,
	[DUNS] [varchar](9) NULL,
	[DUNSP4] [char](4) NULL,
UNIQUE NONCLUSTERED 
(
	[CLIENT] ASC,
	[ADDRNUMBER] ASC,
	[DATE_FROM] ASC,
	[NATION] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
)