CREATE TABLE [dbo].[EKET](
	[TAS_RP_INSERT_DATE] [date] NULL,
	[TAS_RP_CHANGE_DATE] [date] NULL,
	[TAS_RP_OPCODE] [char](1) NULL,
	[TAS_RP_CYCLEID] [bigint] NULL,
	[TAS_RP_COMMIT_SCN] [decimal](20, 0) NULL,
	[MANDT] [char](3) NOT NULL,
	[EBELN] [varchar](10) NOT NULL,
	[EBELP] [varchar](5) NOT NULL,
	[ETENR] [char](4) NOT NULL,
	[EINDT] [varchar](8) NULL,
	[SLFDT] [varchar](8) NULL,
	[LPEIN] [char](1) NULL,
	[MENGE] [decimal](17, 3) NULL,
	[AMENG] [decimal](17, 3) NULL,
	[WEMNG] [decimal](17, 3) NULL,
	[WAMNG] [decimal](17, 3) NULL,
	[UZEIT] [varchar](6) NULL,
	[BANFN] [varchar](10) NULL,
	[BNFPO] [varchar](5) NULL,
	[ESTKZ] [char](1) NULL,
	[QUNUM] [varchar](10) NULL,
	[QUPOS] [char](3) NULL,
	[MAHNZ] [smallint] NULL,
	[BEDAT] [varchar](8) NULL,
	[RSNUM] [varchar](10) NULL,
	[SERNR] [varchar](8) NULL,
	[FIXKZ] [char](1) NULL,
	[GLMNG] [decimal](17, 3) NULL,
	[DABMG] [decimal](17, 3) NULL,
	[CHARG] [varchar](10) NULL,
	[LICHA] [varchar](15) NULL,
	[CHKOM] [char](1) NULL,
	[VERID] [char](4) NULL,
	[ABART] [char](1) NULL,
	[MNG02] [decimal](18, 3) NULL,
	[DAT01] [varchar](8) NULL,
	[ALTDT] [varchar](8) NULL,
	[AULWE] [varchar](10) NULL,
	[MBDAT] [varchar](8) NULL,
	[MBUHR] [varchar](6) NULL,
	[LDDAT] [varchar](8) NULL,
	[LDUHR] [varchar](6) NULL,
	[TDDAT] [varchar](8) NULL,
	[TDUHR] [varchar](6) NULL,
	[WADAT] [varchar](8) NULL,
	[WAUHR] [varchar](6) NULL,
	[ELDAT] [varchar](8) NULL,
	[ELUHR] [varchar](6) NULL,
	[ANZSN] [decimal](10, 0) NULL,
	[NODISP] [char](1) NULL,
	[GEO_ROUTE] [varchar](10) NULL,
	[ROUTE_GTS] [varchar](10) NULL,
	[GTS_IND] [char](2) NULL,
	[TSP] [varchar](10) NULL,
	[CD_LOCNO] [varchar](20) NULL,
	[CD_LOCTYPE] [char](4) NULL,
	[HANDOVERDATE] [varchar](8) NULL,
	[HANDOVERTIME] [varchar](6) NULL,
	[SEL1] [char](1) NULL,
	[CCI] [char](1) NULL,
	[SEN] [varchar](6) NULL,
	[PSEL] [char](1) NULL,
	[PCCI] [char](1) NULL,
	[PSEN] [varchar](6) NULL,
	[DNO] [varchar](12) NULL,
	[SHM] [char](3) NULL,
	[SMB] [varchar](6) NULL,
	[ECC] [varchar](7) NULL,
	[PLC] [char](1) NULL,
	[KEY_ID] [varchar](16) NULL,
	[OTB_VALUE] [decimal](17, 2) NULL,
	[OTB_CURR] [varchar](5) NULL,
	[OTB_RES_VALUE] [decimal](17, 2) NULL,
	[OTB_SPEC_VALUE] [decimal](17, 2) NULL,
	[SPR_RSN_PROFILE] [char](4) NULL,
	[BUDG_TYPE] [char](2) NULL,
	[OTB_STATUS] [char](1) NULL,
	[OTB_REASON] [char](3) NULL,
	[CHECK_TYPE] [char](1) NULL,
	[DL_ID] [varchar](22) NULL,
	[HANDOVER_DATE] [varchar](8) NULL,
	[NO_SCEM] [char](1) NULL,
	[DNG_DATE] [varchar](8) NULL,
	[DNG_TIME] [varchar](6) NULL,
	[CNCL_ANCMNT_DONE] [char](1) NULL,
	[DATESHIFT_NUMBER] [smallint] NULL,
PRIMARY KEY CLUSTERED 
(
	[MANDT] ASC,
	[EBELN] ASC,
	[EBELP] ASC,
	[ETENR] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
)