CREATE TABLE [dbo].[T002](
	[TAS_RP_INSERT_DATE] [varchar](22) NULL,
	[TAS_RP_CHANGE_DATE] [varchar](22) NULL,
	[TAS_RP_OPCODE] [char](3) NULL,
	[TAS_RP_CYCLEID] [varchar](10) NULL,
	[TAS_RP_COMMIT_SCN] [varchar](10) NULL,
	[SPRAS] [char](10) NOT NULL,
	[LASPEZ] [char](10) NULL,
	[LAHQ] [char](10) NULL,
	[LAISO] [char](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[SPRAS] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
)