CREATE TABLE [dbo].[T023T](
	[TAS_RP_INSERT_DATE] [varchar](20) NULL,
	[TAS_RP_CHANGE_DATE] [varchar](20) NULL,
	[TAS_RP_OPCODE] [char](1) NULL,
	[TAS_RP_CYCLEID] [varchar](20) NULL,
	[TAS_RP_COMMIT_SCN] [varchar](20) NULL,
	[MANDT] [char](3) NOT NULL,
	[SPRAS] [char](2) NOT NULL,
	[MATKL] [varchar](9) NOT NULL,
	[WGBEZ] [varchar](20) NULL,
	[WGBEZ60] [varchar](60) NULL,
PRIMARY KEY CLUSTERED 
(
	[MANDT] ASC,
	[SPRAS] ASC,
	[MATKL] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
)