CREATE TABLE [dbo].[T134](
	[TAS_RP_INSERT_DATE] [varchar](20) NULL,
	[TAS_RP_CHANGE_DATE] [varchar](20) NULL,
	[TAS_RP_OPCODE] [char](1) NULL,
	[TAS_RP_CYCLEID] [varchar](20) NULL,
	[TAS_RP_COMMIT_SCN] [varchar](20) NULL,
	[MANDT] [char](3) NOT NULL,
	[MTART] [char](4) NOT NULL,
	[MTREF] [char](4) NULL,
	[MBREF] [char](4) NULL,
	[FLREF] [char](4) NULL,
	[NUMKI] [char](2) NULL,
	[NUMKE] [char](2) NULL,
	[ENVOP] [char](1) NULL,
	[BSEXT] [char](1) NULL,
	[BSINT] [char](1) NULL,
	[PSTAT] [varchar](15) NULL,
	[KKREF] [char](4) NULL,
	[VPRSV] [char](1) NULL,
	[KZVPR] [char](1) NULL,
	[VMTPO] [char](4) NULL,
	[EKALR] [char](1) NULL,
	[KZGRP] [char](1) NULL,
	[KZKFG] [char](1) NULL,
	[BEGRU] [char](4) NULL,
	[KZPRC] [char](1) NULL,
	[KZPIP] [char](1) NULL,
	[PRDRU] [char](1) NULL,
	[ARANZ] [char](1) NULL,
	[WMAKG] [char](1) NULL,
	[IZUST] [char](1) NULL,
	[ARDEL] [char](4) NULL,
	[KZMPN] [char](1) NULL,
	[MSTAE] [char](2) NULL,
	[CCHIS] [char](1) NULL,
	[CTYPE] [char](3) NULL,
	[CLASS1] [varchar](18) NULL,
	[CHNEU] [char](1) NULL,
	[VTYPE] [varchar](10) NULL,
	[VNUMKI] [char](2) NULL,
	[VNUMKE] [char](2) NULL,
	[KZFFF] [char](1) NULL,
	[KZRAC] [char](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[MANDT] ASC,
	[MTART] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
)